---
name: VanillaEnchantments
version: 3.1.0_ALPHA
api:
- 3.1.1
- 3.0.1
- 3.0.2
- 3.0.3
author: TheAz928
website: Github.com/TheAz928/VanillaEnchantments
main: vanilla\Core
description: "Vanilla enchantments implemention for pmmp"

...
